### ISSUE TITLE
Datatype vs. data-type format between swc-blueprint and datashuttle docs.

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/SWC-Blueprint#27]
In SWC-Blueprint documentation data type is written _datatype_ (when not in backticks). This makes nice consistency where it appears in backticks e.g. `datatype`. For datashuttle docs, I realised it is _data-type_, so would be nice to have this consistent across website. 

It may make sense to remove `datatype` from backtick in the specification, as its not something that is written in real projects (e.g. unlike `behav`, `ephys`). I see in bids they use `datatype` during [examples](https://bids-specification.readthedocs.io/en/stable/05-derivatives/02-common-data-types.html#preprocessed-or-cleaned-data), so we could stick with this.

I think _data-type_ is a little more readable, but _datatype_ is nice as it is consistent with `datatype` examples in backticks, if we stick with them.

**Comment by niksirbi** [comment]
So how about we keep spelling it as *datatype*, same as BIDS, but I remove the backticks from `datatype` because you are right about it not appearing in the project tree. I am willing to implement this here and you can do the same for `DataShuttle`.
