### ISSUE TITLE
Consider renaming to NeuroBlueprint

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/SWC-Blueprint#34]
The "SWC" in the name may give the impression that the specification is only meant for one institute. "Neuro" makes it more general.

**Comment by bendichter** [comment]
As a naive outsider, I would encourage this name change. It is not clear to me from the current name that the standard is for neurophysiology data.

**Comment by adamltyson** [comment]
@niksirbi @JoeZiminski I think we should just go ahead and rename it now. It'll only get more confusing if we leave it longer.

**Comment by niksirbi** [comment]
I'm happy to take this on. Just to be sure, are we fine with `NeuroBlueprint` (CamelCase)?

**Comment by JoeZiminski** [comment]
Thanks Ben and Thanks Niko for taking this on!
